// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsIscLauQAm7WMFdVk7hEY7PjwMg2kqQ4',
    appId: '1:1033870852178:web:12ad49728a350791329f8b',
    messagingSenderId: '1033870852178',
    projectId: 'snapflix-255d8',
    authDomain: 'snapflix-255d8.firebaseapp.com',
    storageBucket: 'snapflix-255d8.appspot.com',
    measurementId: 'G-CY5JJ3FFW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAriU5xtDFzCO-obwnX6EPHUdrEeX3o6w8',
    appId: '1:1033870852178:android:c677da197276be30329f8b',
    messagingSenderId: '1033870852178',
    projectId: 'snapflix-255d8',
    storageBucket: 'snapflix-255d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAFCeZl3Fgw-t_SHE5JRguy808ZpuA6L4',
    appId: '1:1033870852178:ios:c9f87f01a170c7bb329f8b',
    messagingSenderId: '1033870852178',
    projectId: 'snapflix-255d8',
    storageBucket: 'snapflix-255d8.appspot.com',
    androidClientId: '1033870852178-r1pu7k2r13bke5gkg49ke015ntc0g27t.apps.googleusercontent.com',
    iosClientId: '1033870852178-qnc35674sk4qli40fdjspkeco4bmt2c7.apps.googleusercontent.com',
    iosBundleId: 'com.app.snapflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAFCeZl3Fgw-t_SHE5JRguy808ZpuA6L4',
    appId: '1:1033870852178:ios:2cef3994c245d0e7329f8b',
    messagingSenderId: '1033870852178',
    projectId: 'snapflix-255d8',
    storageBucket: 'snapflix-255d8.appspot.com',
    androidClientId: '1033870852178-r1pu7k2r13bke5gkg49ke015ntc0g27t.apps.googleusercontent.com',
    iosClientId: '1033870852178-ct6cjbokeoqkbj88fq1p5j46ijusu30p.apps.googleusercontent.com',
    iosBundleId: 'com.app.snapflix.RunnerTests',
  );
}
